
name: Deploy Jekyll site preview

on:
  pull_request:
    types:
    - opened
    - synchronize

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

concurrency: preview-${{ github.ref }}

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Ruby
        # https://github.com/ruby/setup-ruby/releases/tag/v1.207.0
        uses: ruby/setup-ruby@4a9ddd6f338a97768b8006bf671dfbad383215f4
        with:
          ruby-version: '3.3' # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
          cache-version: 1 # Increment this number if you need to re-download cached gems
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5
      - name: Build with Jekyll
        # Outputs to the './_site' directory by default
        run: bundle exec jekyll build --baseurl "${{ steps.pages.outputs.base_path }}"
        env:
          JEKYLL_ENV: production
      - name: Upload artifact
        # Automatically uploads an artifact from the './_site' directory by default
        uses: actions/upload-pages-artifact@v3


  # Display preview job
  display-preview:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy preview
        uses: actions/checkout@v4
      - name: Deploy preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: .
          github-token: ${{ secrets.GITHUB_TOKEN }}
          umbrella-dir: pr-preview
          action: auto
          preview-branch: ${{ github.head_ref }}
